image: docker:20.10.14

stages:
  - build

Docker_build:
  stage: build
  services:
    - docker:20.10.14-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
#    - DOCKER_BUILDKIT=1 docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA --output lib1/ .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - pwd
    - echo $CI_BUILDS_DIR
    - echo $CI_PROJECT_PATH
#    - docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - docker rm -f re2-libsass
    - docker run -d -it --name re2-libsass $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - docker cp re2-libsass:/usr/src/app/re2/obj/ ./
    - docker cp re2-libsass:/usr/src/app/libsass/lib/ ./
    - docker rm -f re2-libsass
  artifacts:
    name: $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    paths:
      - lib/
      - obj/
    expire_in: 3 days
  when: manual
  tags:
    - re2-libsass


